### ISSUE TITLE
Cobalt 2 seems to be abandoned!

### ISSUE THREAD

**Issue by bauerbach** [ebernerd/Cobalt-2#1]
Cobalt 2 was last updated 2 years ago! Is it still being developed?

The Discord server appears to also have been shut down (I got an "Invite Invalid" error message when I tried to join it which can be a sign that the server no longer exists). What a shame; this was a very good project and now it's no longer in development, AND it was the ONLY one of its kind!

**Comment by ebernerd** [comment]
This project is more in hibernation than abandoned. I'm sorry to hear the Discord link expired. I just generated a new one: https://discord.gg/ZdhMJJ5. I'll update the README to include this new link.

I don't really know what to update here. I don't touch CC much in my free time anymore so development on this project will be as features are requested. Plus, if you've got ideas for new stuff, you can always clone and make a PR, or fork the repository.

Glad to see people still have interest in this stuff though! Never thought software I wrote for a video game computer would still be used this far along in the future :)
